return {
		
		ANNOUNCE_REFUSE_BOAT1 = "Musha can't eat on the boat !",
		ANNOUNCE_REFUSE_BOAT2 = "Whatever, just don't spew on the boat.",
		ANNOUNCE_REFUSE_BOAT3 = "if Musha eat a something, probably feel like going to vomit.",
		
		ANNOUNCE_FULLBELLY = "can't eat anymore!",
		ANNOUNCE_HATEFOOD = "Eww!",
		
        ANNOUNCE_ADVENTUREFAIL = "No.. can't fail now..",
        ANNOUNCE_BOOMERANG = "Stupid woodstick!",
        ANNOUNCE_CHARLIE = "Not afraid of you! The crown is mine!",
        ANNOUNCE_CHARLIE_ATTACK = "OUCH! Stop hiding!",
        ANNOUNCE_COLD = "Ah! Musha's fingers are freezing!",
        ANNOUNCE_HOT = "It's so hot!",
        ANNOUNCE_DUSK = "Night is coming..",
        ANNOUNCE_EAT =
        {
                GENERIC = "Yum!",
                PAINFUL = "Ew!",
                SPOILED = "Tastes like Beefalo manure!",
                STALE = "Bleh!",
        },
        ANNOUNCE_HOUNDS = "Come out and fight!",
        ANNOUNCE_HUNGRY = "So hungry..",
        ANNOUNCE_HUNT_BEAST_NEARBY = "Grr, smells close!",
        ANNOUNCE_HUNT_LOST_TRAIL = "Boo.. Musha lost his scent.",
        ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Boo.. Musha lost his scent.",
        ANNOUNCE_ACCOMPLISHMENT= "No-one is taking my crown!",
        ANNOUNCE_ACCOMPLISHMENT_DONE = "Musha won't stop!",     
        ANNOUNCE_PECKED = "Hey! Knock it off birdbrain!",
        ANNOUNCE_TORCH_OUT = "Torch out!",
        ANNOUNCE_WORMHOLE = "Ewwwww. That was disgusting!",
        ANNOUNCE_TRAP_WENT_OFF = "Eek!",
    ANNOUNCE_CRAFTING_FAIL = "Hm. What is missing?",
    ANNOUNCE_QUAKE = "Everything is shaking!",
    ANNOUNCE_NODANGERSLEEP = "Can't sleep now, have to be on guard.",
    ANNOUNCE_NOHUNGERSLEEP = "Aaah so hungry.. my bed looks tasty.",
    ANNOUNCE_FREEDOM = "Ha! You can't stop Musha!",
    ANNOUNCE_RESEARCH = "It was ok, too many words.",
    ANNOUNCE_NO_TRAP = "Sneaky Musha wins again!",
    ANNOUNCE_HIGHRESEARCH = "Oooh.. Musha's head get larger?",
    ANNOUNCE_THORNS = "Ow! Rude plants!",
    ANNOUNCE_NODAYSLEEP_CAVE = "Musha can't sleep here, it makes my fur crawl.",
    ANNOUNCE_BEES = "Buzzbugs!",
    ANNOUNCE_KNOCKEDOUT = "Oh.. spinning little stars..",
    ANNOUNCE_LOWRESEARCH = "Musha liked that one, it had pictures.",
    ANNOUNCE_DEERCLOPS = "Hm. Musha's nose says danger!",
    ANNOUNCE_MOSQUITOS = "Musha bite you back, bugs!",
    ANNOUNCE_NODAYSLEEP = "Sleep? Musha wants to run around!",
    ANNOUNCE_INSUFFICIENTFERTILIZER = "Guess that's not tasty to plants..",
        ANNOUNCE_CANFIX = "\nMusha can fix this!",
        ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Glad that wasn't me.",
        BATTLECRY =
        {
                GENERIC = "Fight me!",
                PIG = "You'll be bacon!",
                PREY = "Grr!",
                SPIDER = "Smash!",
                SPIDER_WARRIOR = "Attack!",
        },
        COMBAT_QUIT =
        {
                GENERIC = "That's what Musha thought!",
                PIG = "Hey! Get back here!",
                PREY = "Get you next time!",
                SPIDER = "Bugs drool!",
                SPIDER_WARRIOR = "Run away little bug!",
        },
        DESCRIBE =
        {
                GLOWDUST ="This is Moon-sugar",
                MUSHA_EGG ="Warm.. Probably can be hatched.",
                MUSHA_EGG1 ="Little guy is getting ready for adventure?",
                MUSHA_EGG2 ="Seems a little cramped..",
                MUSHA_EGG3 ="Go! Go! Adventure!",
                MUSHA_EGGS1 ="Go! Go! Escape!",
                MUSHA_EGGS2 ="Go! Go! Escape!",
                MUSHA_EGGS3 ="Go! Go! Escape!",
                MUSHA_EGG8 ="Finally, the newly born!",

                 GHOSTHOUND = "Ancient dog, Protect me !",
                 GHOSTHOUND2 = "Ancient puppy, Follow me !",
                MUSHA_FLUTE = "Yamche loved my melody",
 
        BOOK_BIRDS = "Book on bird calls.",
        BOOK_TENTACLES = "Secrets of the slimy things.",
        BOOK_GARDENING = "Everything on raising plants",
        BOOK_SLEEP = "A really boring book.",
        BOOK_BRIMSTONE = "Not a good book..",
 
                WORMLIGHT = "Pretty! Can Musha have it?",
                WORM =
                {
                    PLANT = "Oh.. look at that!",
                    DIRT = "This doesn't smell right.",
                    WORM = "Ah! Kill it!",
                },
                EEL = "Ew, slimy!",
                EEL_COOKED = "Musha still not keen on it.",
                UNAGI = "Didn't think this would be edible.",
                EYETURRET = "It fights for me!",
                EYETURRET_ITEM = "Hey you, do something!",
                MINOTAURHORN = "So mighty!",
                MINOTAURCHEST = "Think of the treasure!",
                THULECITE_PIECES = "These little pieces fit together.",
                POND = "No time for a bath.",
                POND_ALGAE = "Aw. No Gobblers hiding here.",
                GREENSTAFF = "It feels magical.",
                POTTEDFERN = "A plant with a little house.",
 
                THULECITE = "Feels old, smells old.. tastes old!",
                ARMORRUINS = "So light but feels strong!",
                RUINS_BAT = "Feels more than just a club.",
                RUINSHAT = "Musha shouldn't wear someone elses crown..",
                NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
                {
                        CALM = "The medallion looks normal.",   --Calm phase
                        WARN = "There is a little glow.",       --Before nightmare
                        WAXING = "It's starting!", --Nightmare Phase first 33%
                        STEADY = "Musha can feel it vibrating!", --Nightmare 33% - 66%
                        WANING = "It's calming down.", --Nightmare 66% +
                        DAWN = "It's gone dark again", --After nightmare
                        NOMAGIC = "Nothing unusual.", --Place with no nightmare cycle.
                },
                BISHOP_NIGHTMARE = "How long has he been here?",
                ROOK_NIGHTMARE = "Musha doesn't like this one at all.",
                KNIGHT_NIGHTMARE = "Looks pretty worn down.",
                MINOTAUR = "Minotaurs are real?",       --Monster in labyrinth
                SPIDER_DROPPER = "Stay out of my hair!",        --White spider that comes from the roof
                NIGHTMARELIGHT = "These lights make my eyes ache.",     --Lights that activate during nightmare.
                GREENGEM = "Apple flavor. Feels light.",
                RELIC = "No scent, everyone left long ago.",    --Fixed relic
                RUINS_RUBBLE = "Some of the pieces are missing.",       --Broken relic
                MULTITOOL_AXE_PICKAXE = "Fear Musha's invention!",      --Works as axe and pickaxe
                ORANGESTAFF = "This is fun!",   --Teleports player.
                YELLOWAMULET = "Shiny and bright!",     --Emits light, player walks faster.
                GREENAMULET = "Gives Musha ideas about how to put things together.",    --Reduce cost of crafting
 
                SLURPER = "Ew! What is that smell?",
                SLURPER_PELT = "Smells even worse now..",
                ARMORSLURPER = "Eeeeeewwwwww!",
                ORANGEAMULET = "Now Musha can take a break.",
                YELLOWSTAFF = "So bright!",
                YELLOWGEM = "Yellow is Musha's favorite!",
                ORANGEGEM = "Nope. Doesn't taste of orange.",
                TELEBASE = 
                {
                        VALID = "Ah! It works!",
                        GEMS = "What's missing?",
                },
                GEMSOCKET = 
                {
                        VALID = "Everything's better with a gem!",
                        GEMS = "Did a bit fall out?",
                },
                STAFFLIGHT = "More! More!",
                RESEARCHLAB4 = "This isn't how hats work.",
        
        ANCIENT_ALTAR =
        {
                WORKING = "Can you hear me ghosties?",
                BROKEN = "Feels cold.",
        },  
  
        ANCIENT_STATUE = "Ick, ugly.",
 
        LICHEN = "Just lichen.",
                CUTLICHEN = "Grr! Why does Musha have to eat plants?",
 
        CAVE_BANANA = "..is it a bug?",
        CAVE_BANANA_COOKED = "Oh! Secret food!",
        CAVE_BANANA_TREE = "Cool tree!",
        ROCKY = "The rocks are alive!",
 
        BLUEAMULET = "Ah! Mhy tonghue shutck tho iht!",
                PURPLEAMULET = "This gives bad feelings..",
                TELESTAFF = "Where do they go?",
                MINERHAT = "Just like a professional!",
                MONKEY = "Stinky fur beasts!",
                MONKEYBARREL = "Smells of fur and poop.",
 
                HOUNDSTOOTH="Musha's teeth are smaller..",
                ARMORSNURTLESHELL="Can Musha sleep in here?",
                BAT="Furry bug!",
                BATBAT = "Bug bat for batting bugs!",
                BATWING="Awww.. Musha can't fly.",
                BATWING_COOKED="Delicious!",
                BEDROLL_FURRY="Oh, so comfy!",
                BUNNYMAN="Oh they look tasty..",
                FLOWER_CAVE="Best plant friend!",
                FLOWER_CAVE_DOUBLE="Best plant friend!",
                FLOWER_CAVE_TRIPLE="Best plant friend!",
                GUANO="Don't they have a bathroom?",
                LANTERN="Better than a torch.",
                LIGHTBULB="How does it glow?",
                MANRABBIT_TAIL="Fluffy fluff!",
                MUSHTREE_TALL="Can Musha be giant too?",
                MUSHTREE_MEDIUM="Fancy pants mushroom.",
                MUSHTREE_SMALL="It's not made of candy, Musha checked!",
                RABBITHOUSE="This is where dinner lives.",
                SLURTLE="Bug with a shell!",
                SLURTLE_SHELLPIECES="Oh, it broke.",
                SLURTLEHAT="Now Musha has a shell too!",
                SLURTLEHOLE="Who's in there?",
                SLURTLESLIME="Ew, slime!",
                SNURTLE="Come back! Musha isn't scary!",
                SPIDER_HIDER="He has armor!",
                SPIDER_SPITTER="Grr, enough spiders!",
                SPIDERHOLE="Full of webs.",
                STALAGMITE="A baby mountain!",
                STALAGMITE_FULL="A baby mountain!",
                STALAGMITE_LOW="A baby mountain!",
                STALAGMITE_MED="A baby mountain!",
                STALAGMITE_TALL="A baby mountain!",
                STALAGMITE_TALL_FULL="A baby mountain!",
                STALAGMITE_TALL_LOW="A baby mountain!",
                STALAGMITE_TALL_MED="A baby mountain!",
                -- Crafted floor items
                TURF_CARPETFLOOR = "The ground is boring.",
                TURF_CHECKERFLOOR = "The ground is boring.",
                TURF_DIRT = "The ground is boring.",
                TURF_FOREST = "The ground is boring.",
                TURF_GRASS = "The ground is boring.",
                TURF_MARSH = "The ground is boring.",
                TURF_ROAD = "The ground is boring.",
                TURF_ROCKY = "The ground is boring.",
                TURF_SAVANNA = "The ground is boring.",
                TURF_WOODFLOOR = "The ground is boring.",
 
                TURF_CAVE="The ground is boring.",
                TURF_FUNGUS="The ground is boring.",
                TURF_SINKHOLE="The ground is boring.",
                TURF_UNDERROCK="The ground is boring.",
                TURF_MUD="The ground is boring.",
 
                TURKEYDINNER = "Now Musha gobble the Gobbler!",
                TWIGS = "Tree antlers!",
                POWCAKE = "Musha not sure this is food..",
        CAVE_ENTRANCE = 
        {
            GENERIC="The hole is jammed with rocks.",
            OPEN = "Looks very dark..",
        },
        CAVE_EXIT = "Back up to the light!",
 
                MAXWELLPHONOGRAPH = "Musha want happy music!",
                PIGGUARD = "Grumpy looking piggy.",
                BOOMERANG = "A stick that comes back!",
                ADVENTURE_PORTAL = "More adventure!",
                AMULET = "Makes me feel safe.",
                ANIMAL_TRACK = "*Sniff* Musha can track him.",
                ARMORGRASS = "Summer dress!",
                ARMORMARBLE = "Clothes made from rock?",
                ARMORWOOD = "It's got splinters.",
                ARMOR_SANITY = "Is it really real?",
                ASH =
                {
                        GENERIC = "The fire burnt it all up.",
                        REMAINS_EYE_BONE = "It burnt up!",
                        REMAINS_THINGIE = "It's gone now..",
                },
                AXE = "First tool for survival!",
                BABYBEEFALO =
                {
                        GENERIC = "Snack sized!.",
                        SLEEPING = "He's snoring",
                },
                BACKPACK = "Room for stuff!",
                BACONEGGS = "Mmm, meat and eggs!",
                BANDAGE = "For dressing wounds.",
                BASALT = "A strong rock!",
                BEARDHAIR = "Who's hair?",
                BEDROLL_STRAW = "Ooh, Muhsa likes to nap.",
                BEE =
                {
                        GENERIC = "Buzzbug!",
                        HELD = "Be good in there.",
                },
                BEEBOX =
                {
                        GENERIC = "Special house for buzzbugs!",
                        READY = "Overflowing with honey!",
                },
                BEEFALO =
                {
                        FOLLOWER = "Does Musha smell good to Beefalo?",
                        GENERIC = "Oh.. looking at them make me hungry.",
                        NAKED = "Silly Beefalo.",
                        SLEEPING = "He looks comfortable.",
                },
                BEEFALOHAT = "This is itchy!",
                BEEFALOWOOL = "Thick, itchy fur.",
                BEEHIVE = "It's noisy.",
                BEEMINE = "They are angry at being locked inside.",
                BEEMINE_MAXWELL = "Musha teach bitebugs a lesson!.",
                BEEHAT = "Now Musha can play with the buzzbugs!",
                BERRIES = "Musha pretend they are candy.",
                BERRIES_COOKED = "No.. still berries.",
                BERRYBUSH =
                {
                        BARREN = "This bush must work harder.",
                        WITHERED = "Aw, it died.",
                        GENERIC = "Looks like nice berries.",
                        PICKED = "Boo. All gone.",
                },
                BIRDCAGE =
                {
                        GENERIC = "A place for new friends!",
                        OCCUPIED = "Stay there!",
                        SLEEPING = "Aw. She tucks her head under her wing to sleep!",
                },
                BIRDTRAP = "Birdies go in. They don't come out!",
                BIRD_EGG = "Packaged food!",
                BIRD_EGG_COOKED = "Delicious!",
                BISHOP = "Mechanical man?",
                BLOWDART_FIRE = "Must be careful!",
                BLOWDART_SLEEP = "Instant nap.",
                BLOWDART_PIPE = "Ninja Musha!",
                BLUEGEM = "Blue like the ocean!",
                BLUEPRINT = "Oh.. Musha had it wrong way up!",
                BLUE_CAP = "Blue is the healthy one.",
                BLUE_CAP_COOKED = "Burnt but tastes better!",
                BLUE_MUSHROOM =
                {
                        GENERIC = "Musha keep on watch for meatshroom.",
                        INGROUND = "Sneaky mushroom!",
                        PICKED = "Do they grow back?",
                },
                BOARDS = "Musha now carpenter!",
                BONESTEW = "Serving size: All of it!",
                BUGNET = "Musha one, Bugs zero!",
                BUSHHAT = "More bush than hat.",
                BUTTER = "For afternoon tea!",
                BUTTERFLY =
                {
                        GENERIC = "It's a flutterbug.",
                        HELD = "Tickly!",
                },
                BUTTERFLYMUFFIN = "Flutterbug cake? Musha confused.",
                BUTTERFLYWINGS = "Aw, poor flutterbug.",
                CAMPFIRE =
                {
                        EMBERS = "Nearly out.",
                        GENERIC = "Fire? Fire!",
                        HIGH = "Oohh.. toasty.",
                        LOW = "Not a lot of heat..",
                        NORMAL = "Yay, marshmallow time!",
                        OUT = "Needs more fuel.",
                },
                CANE = "Time for walkies!",
                CARROT = "Distant cousin of the orange.",
                CARROT_COOKED = "Aw.. veggies..",
                CARROT_PLANTED = "Musha can see you!",
                CARROT_SEEDS = "Baby carrot!",
                CAVE_FERN = "Do you want a pot too?",
                CHARCOAL = "Goodbye tree!",
        CHESSJUNK1 = "Just bits now.",
        CHESSJUNK2 = "So creepy..",
        CHESSJUNK3 = "Is it dead? Good.",
                CHESTER = "Musha likes his horns!",
                CHESTER_EYEBONE =
                {
                        GENERIC = "..looks kinda tasty.",
                        WAITING = "Doesn't do a lot.",
                },
                COOKEDMEAT = "Yay!",
                COOKEDMONSTERMEAT = "Mmm, smells good.",
                COOKEDSMALLMEAT = "Oh.. can Musha have a bigger bit?",
                CORN = "Good if you are a birdie.",
                CORN_COOKED = "The fire broke it!",
                CORN_SEEDS = "Bird food.",
                CROW =
                {
                        GENERIC = "Hi birdie!",
                        HELD = "Musha caught you!",
                },
                CUTGRASS = "Flexible but strong.",
                CUTREEDS = "Tougher than grass.",
                CUTSTONE = "Musha make a castle!",
                DEADLYFEAST = "Smells all wrong.",
                DEERCLOPS = "..Musha leave now, goodbye!",
                DEERCLOPS_EYEBALL = "Musha don't want to touch it!",
                DIRTPILE = "Musha spots something!",
                DIVININGROD =
                {
                        COLD = "Oh, it makes a sound!",
                        GENERIC = "This is a weird stick.",
                        HOT = "Quiet stick thing!",
                        WARM = "More noise!",
                        WARMER = "Beep beep beep!",
                },
                DIVININGRODBASE =
                {
                        GENERIC = "Huh? What's this?",
                        READY = "Does it need something?",
                        UNLOCKED = "It's working!",
                },
                DIVININGRODSTART = "It's a thing that needs other things!",
 
                DRAGONFRUIT = "Wow, cool fruit!",
                DRAGONFRUIT_COOKED = "Mm smells sweet.",
                DRAGONFRUIT_SEEDS = "Musha can grow dragons?",
                DRAGONPIE = "Fruit pie for dessert.",
                DRUMSTICK = "Meat with a handle!",
                DRUMSTICK_COOKED = "Eat you? Ok!",
                DURIAN = "Kill it!",
                DURIAN_COOKED = "It's dead. Good.",
                DURIAN_SEEDS = "No, don't make more!",
                EARMUFFSHAT = "Look cool, feel warm.",
                EGGPLANT = "This is an egg?",
                EGGPLANT_COOKED = "No egg here, just veggie.",
                EGGPLANT_SEEDS = "How Musha tell seeds apart? The smell!",
                STUFFEDEGGPLANT = "More food equals better.",
                DUG_BERRYBUSH = "It's unhappy.",
                DUG_GRASS = "It's unhappy.",
                DUG_MARSH_BUSH = "It's unhappy.",
                DUG_SAPLING = "It's unhappy.",
                EARMUFFS = "Look cool, feel warm.", -- Unused?
                DECIDUOUSTREE = 
                {
                        BURNING = "Poor tree.",
                        BURNT = "It won't grow back..",
                        CHOPPED = "Sorry!",
                        GENERIC = "Just a tree.",
                },
                ACORN = 
                {
                    GENERIC = "Baby tree!",
                    PLANTED = "Looks boring to be a lil tree.",
                },
                EVERGREEN =
                {
                        BURNING = "Poor tree.",
                        BURNT = "It won't grow back..",
                        CHOPPED = "Sorry!",
                        GENERIC = "Just a tree.",
                },
                EVERGREEN_SPARSE =
                {
                        BURNING = "Poor tree.",
                        BURNT = "It won't grow back..",
                        CHOPPED = "Sorry!",
                        GENERIC = "Just a tree.",
                },
                EYEPLANT = "Aha! Proof veggies are evil!",
                FARMPLOT =
                {
                        GENERIC = "Musha the landowner!",
                        GROWING = "Go go, grow grow!",
                        NEEDSFERTILIZER = "Musha think it's hungry.",
                },
                FEATHERHAT = "Bird disguise!",
                FEATHER_CROW = "Crowbird feather. Pretty.",
                FEATHER_ROBIN = "Redbird feather. Pretty.",
                FEATHER_ROBIN_WINTER = "Snowbird feather. Pretty.",
                FEM_PUPPET = "She doesn't smell right.",
                FIREFLIES =
                {
                        GENERIC = "Yay, pretty bugs!",
                        HELD = "So cool!",
                },
                FIREHOUND = "Your fire will not help you beat me!",
                FIREPIT =
                {
                        EMBERS = "Nearly out.",
                        GENERIC = "Fire? Fire!",
                        HIGH = "Oohh.. toasty.",
                        LOW = "Not a lot of heat..",
                        NORMAL = "Yay, marshmallow time!",
                        OUT = "Needs more fuel.",
                },
                FIRESTAFF = "Musha only burn a few things, promise.",
                FISH = "Flippy floppy.",
                FISHINGROD = "For catching floppers.",
                FISHSTICKS = "Bite sized.",
                FISHTACOS = "Easy carry food!",
                FISH_COOKED = "Crisped flopper.",
                FLINT = "Sharp rock.",
                FLOWER = "Hooray!",
                FLOWERHAT = "Something nice for Musha.",
                FLOWER_EVIL = "Grr! You smell wrong!",
                FOLIAGE = "Plant bits.",
                FOOTBALLHAT = "Smells like oinker.",
                FROG =
                {
                        DEAD = "He was rude.",
                        GENERIC = "Hop hop hop.",
                        SLEEPING = "Dreaming of bugs.",
                },
                FROGGLEBUNWICH = "Looks ready to hop away.",
                FROGLEGS = "Too slimey.",
                FROGLEGS_COOKED = "Smells good now.",
                FRUITMEDLEY = "Fruit!",
                GEARS = "Makes stuff go.",
                GHOST = "Can't pick up a scent!",
                GOLDENAXE = "Gold makes everything better!",
                GOLDENPICKAXE = "Gold makes everything better!",
                GOLDENPITCHFORK = "Gold makes everything better!",
                GOLDENSHOVEL = "Gold makes everything better!",
                GOLDNUGGET = "For the royal bank of Musha.",
                GRASS =
                {
                        BARREN = "Wants plant food.",
                        WITHERED = "It dried out.",
                        BURNING = "Fire!",
                        GENERIC = "Grass, not tasty.",
                        PICKED = "Not enough to grab",
                },
                GREEN_CAP = "Makes you very dizzy.",
                GREEN_CAP_COOKED = "Smells better now.",
                GREEN_MUSHROOM =
                {
                        GENERIC = "Musha keep on watch for meatshroom.",
                        INGROUND = "Sneaky mushroom!",
                        PICKED = "Do they grow back?",
                },
                GUNPOWDER = "Be very careful..",
                HAMBAT = "It's also a snack.",
                HAMMER = "For bopping stuff.",
                HEALINGSALVE = "Sticky and smelly.",
                HEATROCK =
                {
                        FROZEN = "Cold as ice!",
                        COLD = "Cool to touch.",
                        GENERIC = "Regular old rock.",
                        WARM = "Snug.",
                        HOT = "Toasty!",
                },
                HOMESIGN = "Musha not actually read sign, just smell it.",
                HONEY = "Liquid happiness!",
                HONEYCOMB = "How do buzzbugs make it?",
                HONEYHAM = "Meat and honey, it's so yummy!",
                HONEYNUGGETS = "Honey snacks.",
                HORN = "Toot toot",
                HOUND = "Bite me!",
                HOUNDMOUND = "They call that a house?",
                HOUNDBONE = "Makes me a bit hungry.",
                ICEBOX = "Where food lives.",
                ICEHOUND = "Frosty the jerkbag",
                INSANITYROCK =
                {
                        ACTIVE = "Musha confused.",
                        INACTIVE = "Rock?",
                },
                JAMMYPRESERVES = "Jam, inferior honey.",
                KABOBS = "Meat with imitation meatbone for carrying.",
                KILLERBEE =
                {
                        GENERIC = "Mean looking buzzbug.",
                        HELD = "No stinging for you!",
                },
                KNIGHT = "Musha can take him.",
                KOALEFANT_SUMMER = "Wooooooooooooow!",
                KOALEFANT_WINTER = "He sure looks warm..",
                KRAMPUS = "Jerk with a jerkbag!",
                KRAMPUS_SACK = "Mine now.",
                LEIF = "Walking tree!",
                LEIF_SPARSE = "Walking tree!",
                LIGHTNING_ROD =
                {
                        CHARGED = "It's making Musha's hair stand up!",
                        GENERIC = "Is it working?",
                },
                LITTLE_WALRUS = "Leave Musha alone!",
                LIVINGLOG = "Cheer up loggy.",
                LOCKEDWES = "He needs help.",
                LOG =
                {
                        BURNING = "Won't burn long.",
                        GENERIC = "Somehow trees are made out of this.",
                },
                LUREPLANT = "Stupid plant. Musha's nose can't be tricked.",
                LUREPLANTBULB = "Could make a good trap.",
                MALE_PUPPET = "He doesn't smell right.",
                MANDRAKE =
                {
                        DEAD = "Even spookier now..",
                        GENERIC = "Spooky plant.",
                        PICKED = "Musha doesn't want to touch it.",
                },
                COOKEDMANDRAKE = "It's looking at me!",
                MANDRAKESOUP = "Spookiness problem solved.",
                MARBLE = "Rock version of candy.",
                MARBLEPILLAR = "Someone sculpted it.",
                MARBLETREE = "Tough tree.",
                MARSH_BUSH =
                {
                        BURNING = "It wasn't very nice.",
                        GENERIC = "Plant with claws.",
                        PICKED = "Ow.",
                },
                MARSH_PLANT = "Just a little plant.",
                MARSH_TREE =
                {
                        BURNING = "Musha didn't like this one.",
                        BURNT = "It won't grow back..",
                        CHOPPED = "Axe beats thorns.",
                        GENERIC = "A mean looking tree.",
                },
                MAXWELL = "What does he want?",
                MAXWELLHEAD = "He sure likes to talk.",
                MAXWELLLIGHT = "Mysterious.",
                MAXWELLLOCK = "Locks want keys.",
                MAXWELLTHRONE = "It's not really a chair..",
                MEAT = "Yeah! Meat!",
                MEATBALLS = "How many can Musha eat at once?",
                MEATRACK =
                {
                        DONE = "Meat time!",
                        DRYING = "Waiting..",
                        DRYINGINRAIN = "This is the opposite of drying.",
                        GENERIC = "Put meat here. Or just eat it!",
                },
                MEAT_DRIED = "Meat chew.",
                MERM = "Musha can smell them no problem.",
                MERMHEAD = "That's what you get for being so stinky!",
                MERMHOUSE = "Stinky, ugly house.",
                MONSTERLASAGNA = "Some don't like it, Musha doesn't mind.",
                MONSTERMEAT = "Different taste, still yummy.",
                MONSTERMEAT_DRIED = "Meat chew.",
                MOSQUITO =
                {
                        GENERIC = "Jerky bitebug.",
                        HELD = "Ugly and dumb.",
                },
                MOSQUITOSACK = "They steal it.",
                MOUND =
                {
                        DUG = "It's empty.",
                        GENERIC = "Dead people and their stuff.",
                },
                NIGHTLIGHT = "Spooky glow.",
                NIGHTMAREFUEL = "Ghost jam!",
                NIGHTSWORD = "Spooks things to death.",
                NITRE = "Colorful rock.",
                ONEMANBAND = "Musha only know how to play one of these.",
                PANDORASCHEST = "Why's it got horns?",
                PANFLUTE = "*Toot*",
                PAPYRUS = "Origami!",
                PENGUIN = "Fish bird!",
                PERD = "Dinner!",
                PEROGIES = "The meat is hidden inside.",
                PETALS = "Colorful.",
                PETALS_EVIL = "All gnarled up.",
                PICKAXE = "Hit rocks to make smaller rocks.",
                PIGGYBACK = "The smell is distracting.",
                PIGHEAD = "Scary..",
                PIGHOUSE =
                {
                        FULL = "Hey! Musha need to use your bathroom!",
                        GENERIC = "Musha prefer her castle back home.",
                        LIGHTSOUT = "They must know the one about the three piggies.",
                },
                PIGKING = "A king shouldn't be lazy!",
                PIGMAN =
                {
                        DEAD = "Pork.",
                        FOLLOWER = "Must keep upwind of him.",
                        GENERIC = "Don't they know about baths?",
                        GUARD = "He doesn't know Musha is a princess.",
                        WEREPIG = "Bad oinker.",
                },
                PIGSKIN = "It's the worst smelling end.",
                PIGTORCH = "They are crazy about it.",
                PINECONE = 
                {
                    GENERIC = "Baby tree!",
                    PLANTED = "Looks boring to be a lil tree.",
                },
                PITCHFORK = "Like a really big fork.",
                PLANTMEAT = "Vegetarian meat?",
                PLANTMEAT_COOKED = "Still not very convincing.",
                PLANT_NORMAL =
                {
                        GENERIC = "Aw, Musha wants meat.",
                        GROWING = "It's growing.",
                        READY = "Bleh. Vegetables.",
                        WITHERED = "Dried out.. plant jerky?",
                },
                POMEGRANATE = "Huh? The berries are inside?",
                POMEGRANATE_COOKED = "Tastes so good!",
                POMEGRANATE_SEEDS = "Looks like a berry.",
                POOP = "It's rude to leave poop around!",
                PUMPKIN = "Yay! Halloweenies!",
                PUMPKINCOOKIE = "Cookies!!",
                PUMPKIN_COOKED = "Not bad for a veggie.",
                PUMPKIN_LANTERN = "Woo! Spooky fun.",
                PUMPKIN_SEEDS = "The secret source of cookies.",
                PURPLEGEM = "Feels odd.",
                RABBIT =
                {
                        GENERIC = "Mr BunBun.",
                        HELD = "That was easy.",
                },
                RABBITHOLE = 
                {
                        GENERIC = "Not a very good house.",
                        SPRING = "This is why you don't build with dirt.",
                },
                RAINOMETER = "If rainometer is wet, it's raining.",
                RATATOUILLE = "Argh, veggies!",
                RAZOR = "Musha doesn't need a haircut.",
                REDGEM = "Strawberry flavor.",
                RED_CAP = "Bad for the stomach.",
                RED_CAP_COOKED = "Doesn't taste of anything.",
                RED_MUSHROOM =
                {
                        GENERIC = "Musha keep on watch for meatshroom.",
                        INGROUND = "Sneaky mushroom!",
                        PICKED = "Do they grow back?",          
                },
                REEDS =
                {
                        BURNING = "Fire!",
                        GENERIC = "Looks like a sausage at the top.",
                        PICKED = "Nothing left.",
                },
        RELIC = 
        {
            GENERIC = "Some kind of something.",
            BROKEN = "It's all bust up.",
        },
        RUBBLE = "Messy rocks.",
                RESEARCHLAB = "This is where science happens!",
                RESEARCHLAB2 = "Twice the science!",
                RESEARCHLAB3 = "Too much science!",
                RESURRECTIONSTATUE = "It's modern art.",
                RESURRECTIONSTONE = "Mystery rocks.",
                ROBIN =
                {
                        GENERIC = "She's a happy birdie.",
                        HELD = "Pocket birdie!",
                },
                ROBIN_WINTER =
                {
                        GENERIC = "That birdie needs a haircut.",
                        HELD = "Fluffy like mittens.",
                },
                ROBOT_PUPPET = "It doesn't smell right.",
                ROCK_LIGHT =
                {
                        GENERIC = "Looks like rock.",
                        OUT = "Just rock.",
                        LOW = "It's dimming.",
                        NORMAL = "Opposite water!"
                },
                ROCKS = "Tastes like rock.",
        ROOK = "Ugly!",
        ROPE = "For tying into knots.",
                ROTTENEGG = "Musha's nose stop working.",
                SANITYROCK =
                {
                        ACTIVE = "Who spent so long carving this?",
                        INACTIVE = "It shrunk?",
                },
                SAPLING =
                {
                        BURNING = "Fire!",
                        WITHERED = "It needs a drink.",
                        GENERIC = "Where twigs are made.",
                        PICKED = "Cheer up tree!",
                },
                SEEDS = "There's a tree in there somewhere.",
                SEEDS_COOKED = "If there's no other food..",
                SEWING_KIT = "Sewing lessons pay off.",
                SHOVEL = "For finding treasure!",
                SILK = "Gross bugs made something nice.",
                SKELETON = "Aah! He's naked!",
                SKULLCHEST = "Looks bad.",
                SMALLBIRD =
                {
                        GENERIC = "Hello shortie.",
                        HUNGRY = "You want some food?",
                        STARVING = "Hungry birdie.",
                },
                SMALLMEAT = "Only a little bit of meat.",
                SMALLMEAT_DRIED = "Tiny snack.",
                SPEAR = "Musha won't be a snack!",
                SPIDER =
                {
                        DEAD = "Bugs deserve it.",
                        GENERIC = "Jerk bug.",
                        SLEEPING = "Still not cute.",
                },
                SPIDERDEN = "Horrible bug house.",
                SPIDEREGGSACK = "Hold very carefully",
                SPIDERGLAND = "Yuck bits.",
                SPIDERHAT = "Musha rather not wear it.",
                SPIDERQUEEN = "Bugbugbugbug!",
                SPIDER_WARRIOR =
                {
                        DEAD = "Later bug face.",
                        GENERIC = "Meaner than most.",
                        SLEEPING = "Bug nap.",
                },
                SPOILED_FOOD = "Musha hate spoiled food!",
                STATUEHARP = "Lame!",
                STATUEMAXWELL = "Statue of a jerk.",
                STINGER = "Butt defense.",
                STRAWHAT = "Summer wear.",
                SUNKBOAT = "Not a safe ocean.",
                SWEATERVEST = "Latest fashion for survival.",
                TAFFY = "Candy! Candyyyyyy!",
                TALLBIRD = "Doesn't look like a friend.",
                TALLBIRDEGG = "Oh, what a snack.",
                TALLBIRDEGG_COOKED = "Breakfast!",
                TALLBIRDEGG_CRACKED =
                {
                        COLD = "Must be cold.",
                        GENERIC = "Contains a pet!",
                        HOT = "Too hot for this one.",
                        LONG = "What's he doing in there?",
                        SHORT = "Come on out!",
                },
                TALLBIRDNEST =
                {
                        GENERIC = "The bird made it.",
                        PICKED = "No eggy.",
                },
                TEENBIRD =
                {
                        GENERIC = "Growing birdie.",
                        HUNGRY = "You want more food?",
                        STARVING = "Ok, Musha will feed you!",
                },
                TELEPORTATO_BASE =
                {
                        ACTIVE = "Musha can leave!",
                        GENERIC = "It works? Really?",
                        LOCKED = "All locked up.",
                        PARTIAL = "Making a.. thing.",
                },
                TELEPORTATO_BOX = "Um..",
                TELEPORTATO_CRANK = "Junk?",
                TELEPORTATO_POTATO = "Clockwork vegetable?",
                TELEPORTATO_RING = "Jewellery?",
                TENT = "House for Musha!",
                TENTACLE = "Purple ones are bad.",
                TENTACLESPOTS = "Ack, gross!",
                TENTACLESPIKE = "For smashing!",
                TENTACLE_PILLAR = "Indoor tree?",
                TENTACLE_PILLAR_ARM = "They came to say hello.",
                TENTACLE_GARDEN = "Musha can hear them underground.",
                TOPHAT = "Next best if you don't have a crown.",
                TORCH = "Musha can smell things but seeing them is good too.",
                TRAP = "Box and stick beats rabbit.",
                TRAP_TEETH = "Mean.",
                TRAP_TEETH_MAXWELL = "Someone tried to hide it.",
                TREASURECHEST = "It's Musha's stuff!",
                TRINKET_1 = "Melted like candy.",
                TRINKET_10 = "Wah? Fake teeth?",
                TRINKET_11 = "A man made of metal.",
                TRINKET_12 = "It's really gross.",
                TRINKET_2 = "It doesn't make a noise.",
                TRINKET_3 = "Knot very useful.",
                TRINKET_4 = "Clay and paint.",
                TRINKET_5 = "What's a rocket?",
                TRINKET_6 = "Rope with metal in it.",
                TRINKET_7 = "Musha too old to play with toys.",
                TRINKET_8 = "A bath would be nice.",
                TRINKET_9 = "No two are the same.",
                TRUNKVEST_SUMMER = "Warm and rainproof.",
                TRUNKVEST_WINTER = "Keeps you warm all day.",
                TRUNK_COOKED = "This is kinda weird.",
                TRUNK_SUMMER = "It could be useful.",
                TRUNK_WINTER = "What a lot of fur.",
                UMBRELLA = "Rain shield.",
                WAFFLES = "Musha will eat you!",
                WALL_HAY = "Not much of a wall.",
                WALL_HAY_ITEM = "Basic.",
                WALL_STONE = "Like a castle!",
                WALL_STONE_ITEM = "Mobile wall.",
                WALL_RUINS = "Built to last.",
                WALL_RUINS_ITEM = "Hard to carry around!",
                WALL_WOOD = "The splinters will help.",
                WALL_WOOD_ITEM = "Very traditional.",
                WALRUS = "What did Musha ever do to you?",
                WALRUSHAT = "Who is the real hunter now?",
                WALRUS_CAMP =
                {
                        EMPTY = "Musha doesn't want to get too close.",
                        GENERIC = "House made of ice? Brr.",
                },
                WALRUS_TUSK = "Can Musha turn into sabretooth?",
                WASPHIVE = "No friendly buzzbugs there.",
                WETGOOP = "The opposite of food!",
                WINTERHAT = "Keeps Musha's ears warm.",
                WINTEROMETER = "It should stay in the middle.",
                WORMHOLE =
                {
                        GENERIC = "Furry ground.",
                        OPEN = "How lazy.",
                },
                ACCOMPLISHMENT_SHRINE = "Does it have a purpose?",                      
        },
        DESCRIBE_TOODARK = "Pitch black!",
        DESCRIBE_SMOLDERING = "It's smoking!",
        EAT_FOOD =
        {
                TALLBIRDEGG_CRACKED = "Ugh. Crunchy.",
        },
}
